// Markdown channel: maintain SUNSHINE.md, a running log of wins (newest first).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { renderMarkdownSection } from '../render.js';

const MARKER = '<!-- sunshine:entries -->';
const HEADER = [
  '# ☀️ Sunshine',
  '',
  'A running log of small, specific wins on this codebase — generated by [sunshine-bot](https://github.com/dwellchecker/sunshine-bot) to keep the good work visible.',
  '',
  MARKER,
  '',
].join('\n');

export function deliver(digest, config, channelCfg, ctx) {
  const path = resolve(ctx.cwd, channelCfg.path || 'SUNSHINE.md');
  const section = renderMarkdownSection(digest, config, { now: ctx.now, slug: ctx.slug });

  let next;
  if (existsSync(path)) {
    const current = readFileSync(path, 'utf8');
    if (current.includes(MARKER)) {
      next = current.replace(MARKER, `${MARKER}\n\n${section.trimEnd()}\n`);
    } else {
      next = `${HEADER}\n${section.trimEnd()}\n\n${current}`;
    }
  } else {
    next = `${HEADER}\n${section.trimEnd()}\n`;
  }

  if (ctx.dryRun) {
    ctx.log(`[dry-run] would write ${path}`);
    return { wrote: false, path };
  }
  writeFileSync(path, next);
  ctx.log(`Updated ${path}`);
  return { wrote: true, path };
}
